var searchData=
[
  ['handlewidth_41021',['handleWidth',['http://doc.qt.io/qt-5/qsplitter.html#handleWidth-prop',1,'QSplitter']]],
  ['hasblurwindow_41022',['hasBlurWindow',['../classDWindowManagerHelper.html#a578fb91ce8d8e2e8da4a5fab2289588f',1,'DWindowManagerHelper']]],
  ['hascomposite_41023',['hasComposite',['../classDWindowManagerHelper.html#a077754f2223ef12dc66d46dc10386ac8',1,'DWindowManagerHelper']]],
  ['hashotspot_41024',['hasHotSpot',['http://doc.qt.io/qt-5/qgesture.html#hasHotSpot-prop',1,'QGesture']]],
  ['hasnotitlebar_41025',['hasNoTitlebar',['../classDWindowManagerHelper.html#abeae2e698f8eed570c5ad5fc79fb41ae',1,'DWindowManagerHelper']]],
  ['hasselectedtext_41026',['hasSelectedText',['http://doc.qt.io/qt-5/qlabel.html#hasSelectedText-prop',1,'QLabel::hasSelectedText()'],['http://doc.qt.io/qt-5/qlineedit.html#hasSelectedText-prop',1,'QLineEdit::hasSelectedText()']]],
  ['haswallpapereffect_41027',['hasWallpaperEffect',['../classDWindowManagerHelper.html#a6d058b14a94b10f269ce7ebeea9c1afd',1,'DWindowManagerHelper']]],
  ['headerhidden_41028',['headerHidden',['http://doc.qt.io/qt-5/qtreeview.html#headerHidden-prop',1,'QTreeView']]],
  ['height_41029',['height',['http://doc.qt.io/qt-5/qwidget.html#height-prop',1,'QWidget::height()'],['http://doc.qt.io/qt-5/qwindow.html#height-prop',1,'QWindow::height()']]],
  ['highlightsections_41030',['highlightSections',['http://doc.qt.io/qt-5/qheaderview.html#highlightSections-prop',1,'QHeaderView']]],
  ['historytype_41031',['historyType',['http://doc.qt.io/qt-5/qhistorystate.html#historyType-prop',1,'QHistoryState']]],
  ['homedir_41032',['homeDir',['../classDAccountsUser.html#a26fae08b2338a66f48d747b79f70e1bb',1,'DAccountsUser']]],
  ['horizontalcenter_41033',['horizontalCenter',['../classDAnchorsBase.html#a312b8194aa10f880a1b4d96557234405',1,'DAnchorsBase']]],
  ['horizontalcenteroffset_41034',['horizontalCenterOffset',['../classDAnchorsBase.html#aa9e852bbe6c864772dad969ee1bec1d2',1,'DAnchorsBase']]],
  ['horizontaldirection_41035',['horizontalDirection',['http://doc.qt.io/qt-5/qswipegesture.html#horizontalDirection-prop',1,'QSwipeGesture']]],
  ['horizontalheaderformat_41036',['horizontalHeaderFormat',['http://doc.qt.io/qt-5/qcalendarwidget.html#horizontalHeaderFormat-prop',1,'QCalendarWidget']]],
  ['horizontalscrollbarpolicy_41037',['horizontalScrollBarPolicy',['http://doc.qt.io/qt-5/qabstractscrollarea.html#horizontalScrollBarPolicy-prop',1,'QAbstractScrollArea']]],
  ['horizontalscrollmode_41038',['horizontalScrollMode',['http://doc.qt.io/qt-5/qabstractitemview.html#horizontalScrollMode-prop',1,'QAbstractItemView']]],
  ['horizontalspacing_41039',['horizontalSpacing',['http://doc.qt.io/qt-5/qformlayout.html#horizontalSpacing-prop',1,'QFormLayout::horizontalSpacing()'],['http://doc.qt.io/qt-5/qgridlayout.html#horizontalSpacing-prop',1,'QGridLayout::horizontalSpacing()']]],
  ['hotspot_41040',['hotSpot',['http://doc.qt.io/qt-5/qgesture.html#hotSpot-prop',1,'QGesture']]],
  ['html_41041',['html',['http://doc.qt.io/qt-5/qtextedit.html#html-prop',1,'QTextEdit']]]
];
