var searchData=
[
  ['valid_36057',['valid',['http://doc.qt.io/qt-5/qmimetype.html#valid-prop',1,'QMimeType']]],
  ['value_36058',['value',['http://doc.qt.io/qt-5/qabstractslider.html#value-prop',1,'QAbstractSlider::value()'],['http://doc.qt.io/qt-5/qspinbox.html#value-prop',1,'QSpinBox::value()'],['http://doc.qt.io/qt-5/qprogressdialog.html#value-prop',1,'QProgressDialog::value()'],['http://doc.qt.io/qt-5/qprogressbar.html#value-prop',1,'QProgressBar::value()'],['http://doc.qt.io/qt-5/qlcdnumber.html#value-prop',1,'QLCDNumber::value()'],['http://doc.qt.io/qt-5/qdoublespinbox.html#value-prop',1,'QDoubleSpinBox::value()']]],
  ['version_36059',['version',['../classDAboutDialog.html#a39d193ac1933a74eff47b50e85661918',1,'DAboutDialog']]],
  ['verticalcenter_36060',['verticalCenter',['../classDAnchorsBase.html#a44a33a87a7e13c559dce6fae6ca5c92e',1,'DAnchorsBase']]],
  ['verticalcenteroffset_36061',['verticalCenterOffset',['../classDAnchorsBase.html#ae12e57aa1784328e422f266162231065',1,'DAnchorsBase']]],
  ['verticaldirection_36062',['verticalDirection',['http://doc.qt.io/qt-5/qswipegesture.html#verticalDirection-prop',1,'QSwipeGesture']]],
  ['verticalheaderformat_36063',['verticalHeaderFormat',['http://doc.qt.io/qt-5/qcalendarwidget.html#verticalHeaderFormat-prop',1,'QCalendarWidget']]],
  ['verticalscrollbarpolicy_36064',['verticalScrollBarPolicy',['http://doc.qt.io/qt-5/qabstractscrollarea.html#verticalScrollBarPolicy-prop',1,'QAbstractScrollArea']]],
  ['verticalscrollmode_36065',['verticalScrollMode',['http://doc.qt.io/qt-5/qabstractitemview.html#verticalScrollMode-prop',1,'QAbstractItemView']]],
  ['verticalspacing_36066',['verticalSpacing',['http://doc.qt.io/qt-5/qformlayout.html#verticalSpacing-prop',1,'QFormLayout::verticalSpacing()'],['http://doc.qt.io/qt-5/qgridlayout.html#verticalSpacing-prop',1,'QGridLayout::verticalSpacing()']]],
  ['viewmode_36067',['viewMode',['http://doc.qt.io/qt-5/qmdiarea.html#viewMode-prop',1,'QMdiArea::viewMode()'],['http://doc.qt.io/qt-5/qlistview.html#viewMode-prop',1,'QListView::viewMode()'],['http://doc.qt.io/qt-5/qfiledialog.html#viewMode-prop',1,'QFileDialog::viewMode()']]],
  ['viewportupdatemode_36068',['viewportUpdateMode',['http://doc.qt.io/qt-5/qgraphicsview.html#viewportUpdateMode-prop',1,'QGraphicsView']]],
  ['virtualdesktop_36069',['virtualDesktop',['http://doc.qt.io/qt-5/qdesktopwidget-obsolete.html#virtualDesktop-prop',1,'QDesktopWidget']]],
  ['virtualgeometry_36070',['virtualGeometry',['http://doc.qt.io/qt-5/qscreen.html#virtualGeometry-prop',1,'QScreen']]],
  ['virtualsize_36071',['virtualSize',['http://doc.qt.io/qt-5/qscreen.html#virtualSize-prop',1,'QScreen']]],
  ['visibility_36072',['visibility',['http://doc.qt.io/qt-5/qwindow.html#visibility-prop',1,'QWindow']]],
  ['visible_36073',['visible',['http://doc.qt.io/qt-5/qaction.html#visible-prop',1,'QAction::visible()'],['http://doc.qt.io/qt-5/qactiongroup.html#visible-prop',1,'QActionGroup::visible()'],['http://doc.qt.io/qt-5/qgraphicsobject.html#visible-prop',1,'QGraphicsObject::visible()'],['http://doc.qt.io/qt-5/qsystemtrayicon.html#visible-prop',1,'QSystemTrayIcon::visible()'],['http://doc.qt.io/qt-5/qwidget.html#visible-prop',1,'QWidget::visible()'],['http://doc.qt.io/qt-5/qinputmethod.html#visible-prop',1,'QInputMethod::visible()'],['http://doc.qt.io/qt-5/qwindow.html#visible-prop',1,'QWindow::visible()']]],
  ['visiblemenucheckboxwidget_36074',['visibleMenuCheckboxWidget',['../classDApplication.html#a8740c958a21ed47cd25bc116c249f7c6',1,'DApplication']]],
  ['visiblemenuicon_36075',['visibleMenuIcon',['../classDApplication.html#a33de68dab5d8008468dd8e4dfb93da59',1,'DApplication']]],
  ['visiblemenushortcuttext_36076',['visibleMenuShortcutText',['../classDApplication.html#a4ce0fec3e460602f631de35803972cd5',1,'DApplication']]]
];
